LibSQL is broken???
```
CREATE TABLE keys (
             public_key BLOB PRIMARY KEY,
             private_key BLOB NOT NULL,
             key_type INTEGER NOT NULL,
             creation_time INTEGER NOT NULL
         );
```

Error: libsql error: SQLite failure: UNIQUE constraint failed: keys.public_key
Caused by:
    SQLite failure: UNIQUE constraint failed: keys.public_key

```
let mut stmt = connection.prepare(
            "INSERT INTO keys (public_key, private_key, key_type, creation_time) VALUES (?1, ?2, ?3, ?4)").await?;
    for key in keys {
        let pre_key = X25519PublicKey::from(key).to_bytes();
        #[allow(deprecated)]
        let pubkey = base64::encode(pre_key);
        info!("Inserting pre key: {pubkey} of type: {key_type}");
        stmt.execute(params![
            pre_key,
            key.to_bytes(),
            key_type as u32,
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs(),
        ])
        .await?;
    }
```

2025-01-18T05:13:00.314750Z  INFO client::client: Inserting pre key: tM6yGfMwWhufYo4wTO5gcTkZegsVkO3sqXhu73B/7AE= of type: OneTimePre
2025-01-18T05:13:00.322918Z  INFO client::client: Inserting pre key: bM7mPksVzhIsTYMUuAkKjulit0/tqBWJJznjHwdqSgU= of type: OneTimePre